apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dns-deception.fullname" . }}
  labels:
    {{- include "dns-deception.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dns-deception.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dns-deception.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5353
              protocol: UDP
            - containerPort: 5353
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "dns-deception.fullname" . }}
          {{- if .Values.secret.decryptionKey }}
            - secretRef:
                name: {{ include "dns-deception.fullname" . }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
