{{- if .Values.secret.decryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dns-deception.fullname" . }}
  labels:
    {{- include "dns-deception.labels" . | nindent 4 }}
type: Opaque
data:
  DECEPTION_SECRET_KEY: {{ .Values.secret.decryptionKey | b64enc }}
{{- end }}
